
BASE_SEARCH_URL: "https://cima.aemps.es/cima"

BASE_LEAFLET_URL: "https://cima.aemps.es/cima/dochtml/p/"

API_ENDPOINT: "http://localhost:11434/api/generate"

PHARMA_ASSISTANT_LLM: "pharma_assistant"

LANGUAGE_DETECTOR_LLM: "language_detector"
